# Generated by Django 5.2.9 on 2026-01-13 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(db_index=True, default='Guarabira', max_length=50)),
                ('cep', models.CharField(max_length=9, unique=True)),
                ('logradouro', models.CharField(db_index=True, max_length=150)),
                ('bairro', models.CharField(db_index=True, max_length=100)),
                ('tipo_codificacao', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_inicial', models.CharField(blank=True, max_length=15, null=True)),
                ('numero_final', models.CharField(blank=True, max_length=15, null=True)),
                ('trecho', models.CharField(blank=True, max_length=15, null=True)),
                ('lado', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
